#!/usr/bin/env bash
# generate-state.sh — Generate evolution/STATE.md summary

EVOLUTION_DIR="$(cd "$(dirname "$0")" && pwd)"
GARDEN_DIR="$(dirname "$EVOLUTION_DIR")/garden"
STATE="$EVOLUTION_DIR/STATE.md"
NOW=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

# --- Last 5 tick-journal entries ---
JOURNAL_SECTION=""
if [ -f "$EVOLUTION_DIR/tick-journal.md" ]; then
  # Get last 5 ## sections
  JOURNAL_SECTION=$(awk '/^## /{n++} n>0{print} n>=5{exit}' RS='## ' ORS='## ' "$EVOLUTION_DIR/tick-journal.md" | tail -c 3000)
fi

# --- Frontier scores ---
FRONTIER_SECTION="*No frontier scores yet*"
if [ -f "$EVOLUTION_DIR/signals/frontier-scores.json" ]; then
  FRONTIER_SECTION=$(cat "$EVOLUTION_DIR/signals/frontier-scores.json")
fi

# --- Garden status ---
GARDEN_SECTION="*No garden status*"
if [ -f "$GARDEN_DIR/STATUS.md" ]; then
  GARDEN_SECTION=$(head -30 "$GARDEN_DIR/STATUS.md")
fi

# --- Pending bridge requests ---
PENDING_COUNT=$(grep -c 'Status.*pending' "$EVOLUTION_DIR/requests/"*.md 2>/dev/null || echo 0)

# --- Nerve daemon ---
if [ -S "$EVOLUTION_DIR/../nerve/bus.sock" ] || [ -S "/tmp/nerve-bus.sock" ]; then
  NERVE_STATUS="🟢 Running (bus.sock exists)"
else
  NERVE_STATUS="🔴 Down"
fi

# --- Bridge daemon ---
if pgrep -f bridge-daemon.js > /dev/null 2>&1; then
  BRIDGE_STATUS="🟢 Running (PID $(pgrep -f bridge-daemon.js | head -1))"
else
  BRIDGE_STATUS="🔴 Down"
fi

# --- Experiments count ---
EXP_COUNT=0
if [ -f "$EVOLUTION_DIR/signals/experiments.jsonl" ]; then
  EXP_COUNT=$(wc -l < "$EVOLUTION_DIR/signals/experiments.jsonl" | tr -d ' ')
fi

# --- Write STATE.md ---
cat > "$STATE" << STATEEOF
# Evolution Engine State

*Generated: $NOW*

## System Health

| Component | Status |
|-----------|--------|
| Bridge Daemon | $BRIDGE_STATUS |
| Nerve Daemon | $NERVE_STATUS |
| Pending Requests | $PENDING_COUNT |
| Total Experiments | $EXP_COUNT |

## Recent Ticks (last 5)

\`\`\`
$JOURNAL_SECTION
\`\`\`

## Frontier Scores

\`\`\`json
$FRONTIER_SECTION
\`\`\`

## Garden Summary

$GARDEN_SECTION

---
*Auto-generated by generate-state.sh*
STATEEOF

echo "STATE.md written to $STATE"
